### ISSUE TITLE
Follow core experience form submission view model changes

### ISSUE THREAD

**Issue by adamsilver** [Financial-Times/next-myft-ui#17]
When the anonymous my ft flag is turned on and the user is anonymous and the user tries to follow a topic, via submitting the form (no JS) the viewModel should contain a notification property, otherwise it should be null/falsy

{ notification: { message: ‘You must be subscribed to follow. Please <a href=”yada”>subscribe</a>’ } }

**Comment by laurieboyes** [comment]
No longer relevant. Attempting to follow/save when anonymous and on core experience now causes redirect to product tour
