### ISSUE TITLE
Make aria labels for n-myft-ui__button more informative

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/next-myft-ui#84]
Currently, the follow buttons all have the same aria-label which means that if you browse the page by landmarks you get this:

![img_1019](https://cloud.githubusercontent.com/assets/68009/11660787/a97903de-9dc6-11e5-92dc-c6bbb294799d.JPG)

(apologies for the shonky phone photo, it's actually surprisingly difficult to screen grab a Voice Over overlay and I've forgotten how to do it)

A neat improvement to this would be to change the text to something like "Follow [the topic] button". 

Also, in case you were wondering, the duplication of "follow" here is happening because Chrome puts the button text and then the aria label next to each other. It only reads out the aria label. This is a feature of chrome but not safari, which typically has better performance when it comes to accessibility.

**Comment by keirog** [comment]
Fixed in https://github.com/Financial-Times/next-myft-ui/pull/117
