### ISSUE TITLE
Replace clientside node-uuid dependency with much smaller uuid stuff

### ISSUE THREAD

**Issue by laurieboyes** [Financial-Times/next-myft-ui#96]
As pointed out by @i-like-robots, node-uuid adds a lot of stuff to the javascript bundle: https://financialtimes.slack.com/archives/ft-next-dev/p1452514906001432
As pointed out by @commuterjoy, this could be replaced with this much lighter solution used by o-tracking: https://github.com/Financial-Times/o-tracking/blob/master/src/libs/browser-cuid.js

**Comment by i-like-robots** [comment]
Is this done?

**Comment by keirog** [comment]
[Yep](https://github.com/Financial-Times/next-myft-ui/pull/119)!
